name: Firmware Build

on:
  push:
    branches:
      - main
  # Manual trigger on UI.
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Import dependency vars
        run: |
          while read line; do
            [[ "$line" == "##"* ]] && break
            [[ "$line" != "" ]] && [[ "$line" != "#"* ]] && echo "$line"
            [[ "$line" != "" ]] && [[ "$line" != "#"* ]] && echo "$line" >> $GITHUB_ENV
          done < scripts/install.sh

      - name: Dependencies from cache
        id: cache-deps
        uses: actions/cache@v4
        with:
          path: deps/
          # Unique identifier by concatenation.
          key: pico-sdk_${{ env.SDK_TAG }}_${{ env.ARM_FILENAME_LINUX_X86_64 }}_v4

      - name: Dependencies from internet
        if: steps.cache-deps.outputs.cache-hit != 'true'
        run: make install

      - name: Build
        run: |
          VERSION=$(echo ${GITHUB_REF} | sed 's|refs/tags/||; s|refs/heads/||; s|[.-]|_|g')
          echo "VERSION=$VERSION" >> $GITHUB_ENV
          echo "VERSION=$VERSION"

          make clean
          DEVICE=alpakka_v0 make
          mv build/alpakka.uf2 alpakka_pico_${VERSION}.uf2

          make clean
          DEVICE=alpakka_v1 make
          mv build/alpakka.uf2 alpakka_marmota_${VERSION}.uf2

          make clean
          DEVICE=dongle make
          mv build/alpakka.uf2 dongle_marmota_${VERSION}.uf2

          ls -l
          shasum alpakka_pico_${VERSION}.uf2
          shasum alpakka_marmota_${VERSION}.uf2
          shasum dongle_marmota_${VERSION}.uf2

          echo -e "\
          =================================
          This firmware build was automated
          =================================

          Branch / Tag:
          ${GITHUB_REF}

          Commit:
          ${GITHUB_SHA}

          Checksum:
          \$ shasum <filename>
          $(cat alpakka_pico_${VERSION}.uf2 | shasum | head -c 40)
          $(cat alpakka_marmota_${VERSION}.uf2 | shasum | head -c 40)
          $(cat dongle_marmota_${VERSION}.uf2 | shasum | head -c 40)

          Job:
          ${GITHUB_SERVER_URL}/${GITHUB_REPOSITORY}/actions/runs/${GITHUB_RUN_ID}
          " > metadata.txt

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: alpakka_artifacts
          path: |
            alpakka_pico_${{env.VERSION}}.uf2
            alpakka_marmota_${{env.VERSION}}.uf2
            dongle_marmota_${{env.VERSION}}.uf2
            metadata.txt
